// SERVER-ONLY (node:crypto — never import from client code).
//
// HMAC turn proofs: the integrity layer that lets /api/roleplay-sessions
// derive pass/fail and warmth_score server-side without trusting the client.
//
// /api/roleplay signs each turn's warmth into a proof token the moment it is
// generated; the client only carries the tokens and hands them back when the
// session is logged. Each proof commits to the SHA-256 of the previous one,
// so a chain can't be reordered, cherry-picked, or spliced across sessions.
//
// Token format:  base64url(JSON payload) + '.' + base64url(HMAC-SHA256)
// Payload:       { v, a: authId, s: scenarioId, t: turnIndex (1-based),
//                  w: warmth (1-10), p: sha256(prev token) or '', ts }
//
// The secret is ROLEPLAY_PROOF_SECRET (>= 32 chars). When it is not set,
// signing is unavailable: roleplay still works, but sessions land with
// verified = FALSE (the same accept-and-flag path as pre-rollout clients) —
// and a loud server log points at the missing config.

import { createHash, createHmac, timingSafeEqual } from 'node:crypto';

const PROOF_VERSION = 1;
// A session's proofs must be redeemed within this window of the first turn —
// bounds how long a captured chain stays usable (replay is also blocked
// outright by the proof_chain_hash unique index).
const PROOF_MAX_AGE_MS = 12 * 60 * 60 * 1000;
// Tolerance for client/server clock skew on "ts is not in the future".
const CLOCK_SKEW_MS = 60_000;

interface ProofPayload {
  v: number;
  a: string;   // auth user id the turn was generated for
  s: string;   // scenario id
  t: number;   // turn index, 1-based, contiguous
  w: number;   // warmth 1-10 as generated by /api/roleplay
  p: string;   // sha256(previous proof token), '' for the first turn
  ts: number;  // ms epoch at signing time
}

let warnedMissingSecret = false;

function getSecret(): string | null {
  const s = process.env.ROLEPLAY_PROOF_SECRET;
  if (s && s.length >= 32) return s;
  if (!warnedMissingSecret) {
    warnedMissingSecret = true;
    console.error(
      '[roleplay-proof] ROLEPLAY_PROOF_SECRET is not set (or shorter than 32 chars) — ' +
      'turn proofs are DISABLED and every roleplay session will be stored unverified.'
    );
  }
  return null;
}

export function hashProofToken(token: string): string {
  return createHash('sha256').update(token).digest('base64url');
}

function signPayload(payloadB64: string, secret: string): string {
  return createHmac('sha256', secret).update(payloadB64).digest('base64url');
}

function parseAndVerifyToken(token: string, secret: string): ProofPayload | null {
  const dot = token.lastIndexOf('.');
  if (dot <= 0) return null;
  const payloadB64 = token.slice(0, dot);
  const sig = token.slice(dot + 1);
  const expected = signPayload(payloadB64, secret);
  const sigBuf = Buffer.from(sig);
  const expectedBuf = Buffer.from(expected);
  if (sigBuf.length !== expectedBuf.length || !timingSafeEqual(sigBuf, expectedBuf)) return null;
  try {
    const payload = JSON.parse(Buffer.from(payloadB64, 'base64url').toString('utf8'));
    if (
      payload?.v !== PROOF_VERSION ||
      typeof payload.a !== 'string' ||
      typeof payload.s !== 'string' ||
      !Number.isInteger(payload.t) || payload.t < 1 ||
      !Number.isInteger(payload.w) || payload.w < 1 || payload.w > 10 ||
      typeof payload.p !== 'string' ||
      !Number.isInteger(payload.ts)
    ) {
      return null;
    }
    return payload as ProofPayload;
  } catch {
    return null;
  }
}

// Sign one turn. `prevProof` chains the token to the run so far; passing an
// invalid/foreign prevProof is an error (the route 400s), not a silent reset.
// Returns null when signing is unavailable (missing secret).
export function signTurnProof(input: {
  authId: string;
  scenarioId: string;
  warmth: number;
  prevProof: string | null;
}): { proof: string } | { error: string } | null {
  const secret = getSecret();
  if (!secret) return null;

  let turnIndex = 1;
  let prevHash = '';
  if (input.prevProof !== null) {
    const prev = parseAndVerifyToken(input.prevProof, secret);
    if (!prev || prev.a !== input.authId || prev.s !== input.scenarioId) {
      return { error: 'Invalid prevProof' };
    }
    turnIndex = prev.t + 1;
    prevHash = hashProofToken(input.prevProof);
  }

  const payload: ProofPayload = {
    v: PROOF_VERSION,
    a: input.authId,
    s: input.scenarioId,
    t: turnIndex,
    w: input.warmth,
    p: prevHash,
    ts: Date.now(),
  };
  const payloadB64 = Buffer.from(JSON.stringify(payload)).toString('base64url');
  return { proof: `${payloadB64}.${signPayload(payloadB64, secret)}` };
}

// Verify a full session's proof chain and extract the trusted per-turn warmth
// values. Any failure returns an error — the caller rejects the log request
// (a broken chain means tampering, not a legacy client; legacy clients send
// no proofs at all).
export function verifyProofChain(input: {
  proofs: string[];
  authId: string;
  scenarioId: string;
  maxTurns: number;
}): { warmths: number[] } | { error: string } {
  const secret = getSecret();
  if (!secret) return { error: 'Proof verification unavailable' };

  const { proofs, authId, scenarioId, maxTurns } = input;
  if (proofs.length === 0) return { error: 'Empty proof chain' };
  if (proofs.length > maxTurns) return { error: 'Too many turns' };

  const now = Date.now();
  const warmths: number[] = [];
  let prevTs = 0;

  for (let i = 0; i < proofs.length; i++) {
    const payload = parseAndVerifyToken(proofs[i], secret);
    if (!payload) return { error: `Invalid proof at turn ${i + 1}` };
    if (payload.a !== authId) return { error: 'Proof was issued to a different user' };
    if (payload.s !== scenarioId) return { error: 'Proof was issued for a different scenario' };
    if (payload.t !== i + 1) return { error: 'Proof chain is out of order' };
    const expectedPrev = i === 0 ? '' : hashProofToken(proofs[i - 1]);
    if (payload.p !== expectedPrev) return { error: 'Proof chain is broken' };
    if (payload.ts < prevTs) return { error: 'Proof timestamps are out of order' };
    if (payload.ts > now + CLOCK_SKEW_MS) return { error: 'Proof timestamp is in the future' };
    prevTs = payload.ts;
    warmths.push(payload.w);
  }

  const firstPayload = parseAndVerifyToken(proofs[0], secret)!;
  if (now - firstPayload.ts > PROOF_MAX_AGE_MS) return { error: 'Proof chain has expired' };

  return { warmths };
}
