export interface StaffMember {
  id: string;
  name: string;
  initials: string;
  role: string;
  dept: string;
  level: number;
  xp: number;
  streak: number;
  score: number;
  lessons: number;
  total: number;
  lastActive: string;
  status: 'star' | 'active' | 'developing' | 'at-risk' | 'new';
  joined: string;
  color: string;
  badges: number;
  skills: {
    greetings: number;
    serviceFlow: number;
    language: number;
    complaints: number;
    floor: number;
    guestPsychology: number;
  };
}

export const SKILL_LABELS: Record<keyof StaffMember['skills'], string> = {
  greetings: 'Greetings',
  serviceFlow: 'Service Flow',
  language: 'Language',
  complaints: 'Complaints',
  floor: 'Floor Work',
  guestPsychology: 'Guest Psychology',
};

export const STAFF: StaffMember[] = [
  {
    id: 's1',
    name: 'Sofía Beltran',
    initials: 'SB',
    role: 'Mesero',
    dept: 'Floor',
    level: 4,
    xp: 720,
    streak: 11,
    score: 93,
    lessons: 23,
    total: 28,
    lastActive: '20m ago',
    status: 'star',
    joined: '2 years ago',
    color: '#81B29A',
    badges: 8,
    skills: { greetings: 96, serviceFlow: 94, language: 92, complaints: 90, floor: 94, guestPsychology: 92 },
  },
  {
    id: 's2',
    name: 'Carlos Marchena',
    initials: 'CM',
    role: 'Capitán',
    dept: 'Floor',
    level: 5,
    xp: 960,
    streak: 18,
    score: 95,
    lessons: 26,
    total: 28,
    lastActive: '5m ago',
    status: 'star',
    joined: '3 years ago',
    color: '#81B29A',
    badges: 11,
    skills: { greetings: 98, serviceFlow: 98, language: 96, complaints: 94, floor: 96, guestPsychology: 94 },
  },
  {
    id: 's3',
    name: 'Anaïs Croes',
    initials: 'AC',
    role: 'Mesero',
    dept: 'Floor',
    level: 3,
    xp: 490,
    streak: 5,
    score: 84,
    lessons: 12,
    total: 28,
    lastActive: '2h ago',
    status: 'active',
    joined: '8 months ago',
    color: '#E07A5F',
    badges: 5,
    skills: { greetings: 88, serviceFlow: 86, language: 82, complaints: 80, floor: 84, guestPsychology: 80 },
  },
  {
    id: 's4',
    name: 'Liam Henriquez',
    initials: 'LH',
    role: 'Runner',
    dept: 'Floor',
    level: 2,
    xp: 250,
    streak: 3,
    score: 68,
    lessons: 7,
    total: 28,
    lastActive: '1d ago',
    status: 'developing',
    joined: '4 months ago',
    color: '#D4A574',
    badges: 2,
    skills: { greetings: 72, serviceFlow: 68, language: 62, complaints: 58, floor: 74, guestPsychology: 60 },
  },
  {
    id: 's5',
    name: 'Valentina Reyes',
    initials: 'VR',
    role: 'Mesero',
    dept: 'Floor',
    level: 3,
    xp: 420,
    streak: 6,
    score: 80,
    lessons: 10,
    total: 28,
    lastActive: '4h ago',
    status: 'active',
    joined: '10 months ago',
    color: '#E07A5F',
    badges: 4,
    skills: { greetings: 84, serviceFlow: 80, language: 78, complaints: 76, floor: 82, guestPsychology: 78 },
  },
  {
    id: 's6',
    name: 'Diego Winklaar',
    initials: 'DW',
    role: 'Runner',
    dept: 'Floor',
    level: 1,
    xp: 90,
    streak: 0,
    score: 38,
    lessons: 2,
    total: 28,
    lastActive: '8 days ago',
    status: 'at-risk',
    joined: '6 weeks ago',
    color: '#C25B43',
    badges: 0,
    skills: { greetings: 42, serviceFlow: 36, language: 30, complaints: 0, floor: 44, guestPsychology: 0 },
  },
  {
    id: 's7',
    name: 'Nadia Zimmerman',
    initials: 'NZ',
    role: 'Mesero',
    dept: 'Floor',
    level: 2,
    xp: 310,
    streak: 2,
    score: 72,
    lessons: 8,
    total: 28,
    lastActive: '6h ago',
    status: 'active',
    joined: '5 months ago',
    color: '#E07A5F',
    badges: 3,
    skills: { greetings: 76, serviceFlow: 72, language: 68, complaints: 70, floor: 74, guestPsychology: 66 },
  },
  {
    id: 's8',
    name: 'Jermaine Cijntje',
    initials: 'JC',
    role: 'Bar Staff',
    dept: 'Bar',
    level: 3,
    xp: 380,
    streak: 4,
    score: 78,
    lessons: 9,
    total: 28,
    lastActive: '3h ago',
    status: 'active',
    joined: '7 months ago',
    color: '#E07A5F',
    badges: 3,
    skills: { greetings: 80, serviceFlow: 78, language: 74, complaints: 72, floor: 80, guestPsychology: 76 },
  },
  {
    id: 's9',
    name: 'Fabiola Noguera',
    initials: 'FN',
    role: 'Bar Staff',
    dept: 'Bar',
    level: 4,
    xp: 680,
    streak: 9,
    score: 89,
    lessons: 20,
    total: 28,
    lastActive: '1h ago',
    status: 'star',
    joined: '1.5 years ago',
    color: '#81B29A',
    badges: 7,
    skills: { greetings: 92, serviceFlow: 90, language: 88, complaints: 86, floor: 90, guestPsychology: 88 },
  },
  {
    id: 's10',
    name: 'Robbie van der Berg',
    initials: 'RB',
    role: 'Runner',
    dept: 'Floor',
    level: 1,
    xp: 50,
    streak: 1,
    score: 28,
    lessons: 1,
    total: 28,
    lastActive: '12 days ago',
    status: 'at-risk',
    joined: '5 weeks ago',
    color: '#C25B43',
    badges: 0,
    skills: { greetings: 30, serviceFlow: 0, language: 24, complaints: 0, floor: 28, guestPsychology: 0 },
  },
  {
    id: 's11',
    name: 'Maria Flores',
    initials: 'MF',
    role: 'Capitán',
    dept: 'Floor',
    level: 4,
    xp: 540,
    streak: 8,
    score: 87,
    lessons: 15,
    total: 28,
    lastActive: '30m ago',
    status: 'active',
    joined: '1 year ago',
    color: '#E07A5F',
    badges: 6,
    skills: { greetings: 90, serviceFlow: 88, language: 84, complaints: 86, floor: 88, guestPsychology: 86 },
  },
  {
    id: 's12',
    name: 'Thijs de Graaf',
    initials: 'TG',
    role: 'Kitchen Liaison',
    dept: 'Operations',
    level: 2,
    xp: 270,
    streak: 2,
    score: 65,
    lessons: 6,
    total: 28,
    lastActive: '1d ago',
    status: 'developing',
    joined: '3 months ago',
    color: '#D4A574',
    badges: 2,
    skills: { greetings: 68, serviceFlow: 66, language: 60, complaints: 62, floor: 70, guestPsychology: 56 },
  },
  {
    id: 's13',
    name: 'Keisha Rosario',
    initials: 'KR',
    role: 'Mesero',
    dept: 'Floor',
    level: 1,
    xp: 60,
    streak: 0,
    score: 22,
    lessons: 1,
    total: 28,
    lastActive: '3h ago',
    status: 'new',
    joined: '1 week ago',
    color: '#8DA9C4',
    badges: 0,
    skills: { greetings: 28, serviceFlow: 0, language: 20, complaints: 0, floor: 22, guestPsychology: 0 },
  },
  {
    id: 's14',
    name: 'Omar Elias',
    initials: 'OE',
    role: 'Manager',
    dept: 'Management',
    level: 5,
    xp: 890,
    streak: 14,
    score: 94,
    lessons: 25,
    total: 28,
    lastActive: '10m ago',
    status: 'star',
    joined: '2.5 years ago',
    color: '#81B29A',
    badges: 10,
    skills: { greetings: 96, serviceFlow: 96, language: 92, complaints: 94, floor: 94, guestPsychology: 92 },
  },
];

export const TREND_DATA = [
  { day: 1, score: 60 }, { day: 3, score: 62 }, { day: 5, score: 61 }, { day: 7, score: 64 },
  { day: 9, score: 66 }, { day: 11, score: 65 }, { day: 13, score: 68 }, { day: 15, score: 67 },
  { day: 17, score: 70 }, { day: 19, score: 71 }, { day: 21, score: 72 }, { day: 23, score: 71 },
  { day: 25, score: 73 }, { day: 27, score: 74 }, { day: 30, score: 75 },
];

export const RECENT_ACTIVITY = [
  { who: 'Carlos Marchena', what: 'completed "The 10-Step Service Flow"', score: 96, when: '5m ago', type: 'completion' as const },
  { who: 'Sofía Beltran', what: 'earned "Floor Master" badge', when: '20m ago', type: 'badge' as const },
  { who: 'Fabiola Noguera', what: 'completed roleplay: Overcooked Burger Complaint', score: 90, when: '1h ago', type: 'roleplay' as const },
  { who: 'Keisha Rosario', what: 'started Lesson 1: The 5-Second Rule', when: '3h ago', type: 'start' as const },
  { who: 'Maria Flores', what: 'completed "Language & Storytelling"', score: 88, when: '30m ago', type: 'completion' as const },
  { who: 'Diego Winklaar', what: 'scored 36 on Service Flow drill', when: '8 days ago', type: 'low-score' as const },
];
